language: python

python:
  - "3.4"

env:
  global:
    secure: "ZUW2raXYAiqfOFpN4aPd9ntc916eVxHJlopASex5nF8LaDYwvNDGSiPlIHsqU6JTttkWCzqPlOC2KPML+evS0hEIgBtAIk1DZncrQU+tLpVvf2jTQnBfq+vuo2acAP2HJCbWmBj9ePKVWiMfjK5+iXY31CzhFl0naYYxlMMt1fc="
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=pypy3
    - TOXENV=pep8

before_install:
  - pip install -U pip tox coveralls wheel setuptools
  - if [[ $TRAVIS_PYTHON_VERSION =~ "2." ]]; then pip install --upgrade futures; fi

script: tox

after_success:
  - coveralls

after_script:
  - INSERTS=$(git diff --shortstat 62d52e04bb86614efc3e6e280b2c9adccddde83f master | cut -d ',' -f2 | awk '{print $1}')
  - DELETES=$(git diff --shortstat 62d52e04bb86614efc3e6e280b2c9adccddde83f master | cut -d ',' -f3 | awk '{print $1}')
  - TOTAL=$(expr $INSERTS + $DELETES)
  - git checkout 62d52e04bb86614efc3e6e280b2c9adccddde83f
  - STARTING=$(git ls-files | xargs wc -l | grep total | awk '{print $1}')
  - DIFF=$(awk "BEGIN {printf \"%.2f\n\", $TOTAL/$STARTING * 100}")
  - git checkout master
  - git config --global user.name "a-tal"
  - git config --global user.email "github@talsma.ca"
  - sed -i -e "s/lines_in-.*/lines_in-$INSERTS-green.svg/" README.rst
  - sed -i -e "s/lines_out-.*/lines_out-$DELETES-red.svg/" README.rst
  - sed -i -e "s/total_change-.*/total_change-$DIFF%-yellow.svg/" README.rst
  - if [[ $TOXENV == "py34" ]]; then git add README.rst; git commit -m '[ci skip] auto updated diff badges'; git push --force "https://$github_token@github.com/a-tal/bladerunner.git" master; fi

before_deploy:
  - python setup.py build sdist bdist_wheel
  - if [ "x" == "$(grep $(git tag -l --points-at=HEAD) bladerunner/__init__.py)x" ]; then echo 'new tag does not exist in __init__.py; bailing!'; exit 1; else echo "tag found in __init__.py"; fi

deploy:
  - provider: pypi
    user: atal
    skip_cleanup: true
    distributions: "sdist bdist_wheel"
    password:
      secure: "X6MZU42NMezgjuIkXE7XF6aZv0KmxKrix8cCJTedRmjYXqSHCqYZ3LCuJdNveRBUG36WZGVYbtDKx96dLwvCIWryOKcdcH7TkrB8CuDCeO39lPr9L7MYWiZX+72Xfi8TL9X8u5RQVoNWAVB7d3CZ4kzylPpot9cm7DbWpmqLSJE="
    on:
      tags: true
      repo: a-tal/bladerunner
      condition: $TOXENV = py34
  - provider: releases
    api_key:
      secure: "h7n+8ndAGOWKNnKdKwTxBhK5sWg3IJ9LMHyvTL1V2paegEtJAqFiP0TaUZGaz8x5fhNcnmQNSAsQzOPMcGSkuO/d13HMvtzs7VvXHw/830c2Nf1ScAdojZKGjNWhB2YPr8EWMLffp7yYNlywhmtegbWpsc0jLWE1nGH7hMGvtnI="
    file: "/home/travis/build/a-tal/bladerunner/dist/*.whl"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: $TOXENV = py34

notifications:
  irc:
    channels: "irc.freenode.org#atal-dev"
    on_success: change
    on_failure: change
